from django.urls import path
from employee.views.group import GroupView
urlpatterns = [
    path("add", GroupView.as_view(), name='__add_groups__'),
    path("list", GroupView.as_view(), name='__get_groups__'),
    path("edit/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("view/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("search", GroupView.as_view(), name='__get_groups__'),
    path("activate/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("deactivate/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("change_permissions/<group_id>",
         GroupView.as_view(), name='__get_groups__'),
    path("assign_users/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("delete_user/<group_id>/<user_id>",
         GroupView.as_view(), name='__get_groups__'),
    path("add_user/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("update_user/<group_id>/<user_id>",
         GroupView.as_view(), name='__get_groups__'),
    path("get_permissions/<group_id>",
         GroupView.as_view(), name='__get_groups__'),
    path("change_permissions/<group_id>/<permission_id>",
         GroupView.as_view(), name='__get_groups__'),
    path("add_permission/<group_id>", GroupView.as_view(), name='__get_groups__'),
    path("delete", GroupView.as_view(), name='__delete_groups__'),
    path("edit", GroupView.as_view(), name='__delete_groups__'),
    path("delete/<group_id>", GroupView.as_view(), name='__get_groups__'),
]
